version: "2"
services:
    apache:
        build: docker/apache
        container_name: servife_apache
        ports: 
            - "8002:80"
        volumes:
            - ./:/var/www/html/
            - ./docker/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
        networks:
            - front-tier
            - back-tier
        restart: always

    mysql:
        image: mysql:5.5
        container_name: servife_mysql
        hostname: db-server
        ports:
            - "3308:3306"
        volumes:
            - ./docker/mysql/database:/docker-entrypoint-initdb.d
        networks:
            - back-tier
        env_file: 
            - ./docker/environments.env
        restart: always
        command: mysqld --sql_mode=""

networks:
    front-tier:
        driver: bridge
    back-tier:
        driver: bridge