version: "2"
services:
    # nginx:
    #     build: docker/nginx
    #     container_name: servife_nginx
    #     ports:
    #         - "8002:80"
    #         - "443:443"
    #     volumes_from:
    #         - php-fpm
    #     networks:
    #         - front-tier

    # php-fpm:
    #     build: docker/php-fpm
    #     container_name: servife_phpfpm
    #     volumes:
    #         - ./:/html/
    #         - ./logs/nginx/:/var/log/nginx/
    #         - ./logs/:/html/var/logs/
    #     networks:
    #         - front-tier
    #         - back-tier

    apache:
        build: docker/apache
        container_name: servife_apache
        ports: 
            - "8002:80"
        volumes:
            - ./:/var/www/html/
            - ./docker/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
        networks:
            - front-tier
            - back-tier
        restart: always

    mysql:
        image: mysql:5.5
        container_name: servife_mysql
        hostname: db-server
        ports:
            - "3308:3306"
        volumes:
            - ./docker/mysql/database:/docker-entrypoint-initdb.d
        networks:
            - back-tier
        env_file: 
            - ./docker/environments.env
        restart: always
        command: mysqld --sql_mode=""

networks:
    front-tier:
        driver: bridge
    back-tier:
        driver: bridge